### ISSUE TITLE
怎么拼接字符串变量 update_message？

### ISSUE THREAD

**Issue by dito010** [thierryxing/dingtalk-bot#2]
```ruby
update_message = <<DESC
App: echo 瞬间
分支: master
CommitSHA: SHA
APNs 推送环境: Production
下载地址: https://www.pgy.com
DESC


DingBot.endpoint='https://oapi.dingtalk.com/robot/send'
DingBot.access_token = 'xxx'

# 发送整体跳转ActionCard消息
def send_whole_action_card
  message = DingBot::Message::WholeActionCard.new(
      'iOS 自动构建成功消息',
      '![screenshot](@lADOpwk3K80C0M0FoA)#{update_message}',
      '点击前往下载',
      'https://www.pgy.com'
  )
  DingBot.send_msg(message)
end
```

**Comment by thierryxing** [comment]
update_message 是一个纯文本消息吗？可以直接用：

```
# 快速发送一套只包含文本的Text消息（不需要构造Message对象）
def send_simple_text
  DingBot.send_text('我就是我, 是不一样的烟火')
end

# 发送复杂Text消息
def send_text
  message = DingBot::Message::Text.new(
      '我就是我, 是不一样的烟火',
      ['1371xxxx117'],
      false
  )
  DingBot.send_msg(message)
end
```

**Comment by dito010** [comment]
```ruby
update_message = <<DESC
App: echo 瞬间
分支: master
CommitSHA: SHA
APNs 推送环境: Production
下载地址: https://www.pgy.com
DESC
```
蟹蟹你的回答 💖。是一个纯文本消息，但是我想用卡片的形式来展示，然后我想把文本消息用作卡片的标题。

**Comment by thierryxing** [comment]
这样就行
```
update_message = <<DESC
App: echo 瞬间
分支: master
CommitSHA: SHA
APNs 推送环境: Production
下载地址: https://www.pgy.com
DESC


DingBot.endpoint='https://oapi.dingtalk.com/robot/send'
DingBot.access_token = 'xxx'

# 发送整体跳转ActionCard消息
def send_whole_action_card
  message = DingBot::Message::WholeActionCard.new(
      'iOS 自动构建成功消息',
     update_message,
      '点击前往下载',
      'https://www.pgy.com'
  )
  DingBot.send_msg(message)
end
```

**Comment by dito010** [comment]
```zsh
➜  Desktop ruby msg.rb
Traceback (most recent call last):
	1: from msg.rb:27:in `<main>'
msg.rb:20:in `send_whole_action_card': undefined local variable or method `update_message' for main:Object (NameError)
```
不行的，报错。

**Comment by thierryxing** [comment]
msg.rb 发我一下，我看看

**Comment by newyjp** [comment]
[msg.rb.zip](https://github.com/thierryxing/dingtalk-bot/files/2655891/msg.rb.zip)

**Comment by thierryxing** [comment]
这样就行，设置成实例变量
```
require "bundler/setup"
require "dingbot"

@update_message = <<DESC
App: echo 瞬间
分支: master
CommitSHA: SHA
APNs 推送环境: Production
下载地址: https://www.pgy.com
DESC

DingBot.endpoint='https://oapi.dingtalk.com/robot/send'
DingBot.access_token = 'd6ab036f650944dabf11aff6f7991d43fe28997795a031e29dccd361724ba297'

puts @update_message

# 发送整体跳转ActionCard消息
def send_whole_action_card
  message = DingBot::Message::WholeActionCard.new(
      'iOS 自动构建成功消息',
      @update_message,
      '点击前往下载',
      'https://www.pgy.com'
  )
  DingBot.send_msg(message)
end

send_whole_action_card
```

**Comment by dito010** [comment]
Thanks very much ❤️

**Comment by dito010** [comment]
如果我想添加一张图片呢？我应该怎么写？

**Comment by dito010** [comment]
![screenshot](https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/07/47/f7/0747f753-f58e-2566-32b8-4ea3e32c6802/source/1024x512bb.jpg) 想把这张图片加上。

**Comment by thierryxing** [comment]
用 markdown 格式的，加个图片链接就行

**Comment by thierryxing** [comment]
```
@update_message = <<DESC
App: echo 瞬间
分支: master
CommitSHA: SHA
APNs 推送环境: Production
下载地址: https://www.pgy.com

DESC
```

**Comment by thierryxing** [comment]
https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.45484a97stJJVP&treeId=257&articleId=105735&docType=1

**Comment by dito010** [comment]
👌
